### ISSUE TITLE
TypeError: save_image() got an unexpected keyword argument 'filename'

### ISSUE THREAD

**Issue by andyandytony** [christopher-beckham/hologan-pytorch#3]
![Screenshot 2020-04-23 18:44:02](https://user-images.githubusercontent.com/50736064/80091183-4276f380-8593-11ea-847e-3154f6d388b3.png)

**Comment by christopher-beckham** [comment]
It appears that the function call has changed in the stable version of torchvision: https://pytorch.org/docs/stable/torchvision/utils.html

It looks like it's now been replaced by `fp`, so rename `filename` to that and see if it works.

**Comment by andyandytony** [comment]
thanks a lots !! @christopher-beckham 
![螢幕快照 2020-04-24 00:02:31](https://user-images.githubusercontent.com/50736064/80121549-078ab500-85bf-11ea-8737-d2fdc13fee86.png)
how about this .!

**Comment by christopher-beckham** [comment]
What dataset are you using? It's complaining that the expected image is 3x32x32 (rgb) but what it's seeing is 1x32x32 (greyscale). The issue looks related to the `Normalize` function in `torchvision.transforms` In that case you probably want to it to subtract and divide by `(0.5,)`, rather than `(0.5, 0.5, 0.5)`

**Comment by christopher-beckham** [comment]
Please consult: https://pytorch.org/docs/stable/torchvision/transforms.html#torchvision.transforms.Normalize

**Comment by christopher-beckham** [comment]
Hmm, if it's CelebA, maybe it's because some images in the dataset are greyscale? If so, take this line:

https://github.com/christopher-beckham/hologan-pytorch/blob/master/iterators/datasets.py#L25

and change:

`img = self.transform(Image.open(filepath))`

to:

`img = self.transform(Image.open(filepath).convert('RGB'))`

That makes sure any images read are converted to RGB. If that is indeed the issue, I will make a commit for it.

**Comment by andyandytony** [comment]
Thx you a lots  .
 It's very nice of you!
running now!!
![3](https://user-images.githubusercontent.com/50736064/80124408-d0b69e00-85c2-11ea-81a2-d8433370a905.png)
 I can't thank you enough.
